USE [ToysAPI]
CREATE TABLE ToyTypes(
	ToyTypeId INT IDENTITY(1,1) PRIMARY KEY,
	ToyTypeName NVARCHAR(30) NOT NULL,
	IsActive BIT DEFAULT 1
)

CREATE TABLE Customers(
	CustomerId INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	UserName NVARCHAR(30) NOT NULL,
	MobileNumber INT NOT NULL,
	IsActive BIT DEFAULT 1
)

CREATE TABLE Toys(
	ToyId INT IDENTITY(1,1) PRIMARY KEY,
	ToyName NVARCHAR(30) NOT NULL,
	Price DECIMAL(6,2) NOT NULL,
	ToyPlantId INT NOT NULL,
	ToyTypeId INT NOT NULL,
	IsActive BIT DEFAULT 1
)
ALTER TABLE Toys WITH CHECK ADD CONSTRAINT FK_ToyPlants FOREIGN KEY(ToyPlantId) REFERENCES ToyPlants(ToyPlantId)
ALTER TABLE Toys WITH CHECK ADD CONSTRAINT FK_ToyTypes FOREIGN KEY(ToyTypeId) REFERENCES ToyTypes(ToyTypeId)

CREATE TABLE Offers(
	OfferId INT IDENTITY(1,1) PRIMARY KEY,
	PerDiscount DECIMAL(4,2) NOT NULL,
	OrderAmount INT NOT NULL,
	IsActive BIT DEFAULT 1
)

CREATE TABLE OrderItems(
	OrderItemId INT IDENTITY(1,1) PRIMARY KEY,
	ToyId INT NOT NULL,
	Quantity INT NOT NULL,
	OrderId INT NOT NULL,
	IsActive BIT DEFAULT 1
)
ALTER TABLE OrderItems WITH CHECK ADD CONSTRAINT FK_OrderItems_Toys FOREIGN KEY(ToyId) REFERENCES Toys(ToyId)
ALTER TABLE OrderItems WITH CHECK ADD CONSTRAINT FK_OrderItems_Orders FOREIGN KEY(OrderId) REFERENCES Orders(OrderId)

CREATE TABLE Orders(
	OrderId INT IDENTITY(1,1) PRIMARY KEY,
	OfferId INT NOT NULL,
	TotalAmount DECIMAL(4,2) NOT NULL,
	NetAmount DECIMAL(4,2) NOT NULL,
	OrderDate DATE NOT NULL,
	CustomerAddressId INT NOT NULL,
	CustomerId INT NOT NULL,
	IsActive BIT DEFAULT 1
)
ALTER TABLE Orders WITH CHECK ADD CONSTRAINT FK_Orders_Offers FOREIGN KEY(OfferId) REFERENCES Offers(OfferId)
ALTER TABLE Orders WITH CHECK ADD CONSTRAINT FK_Orders_CustomerAddress FOREIGN KEY(CustomerAddressId) REFERENCES CustomerAddress(CustomerAddressId)
ALTER TABLE Orders WITH CHECK ADD CONSTRAINT FK_Order_Customer FOREIGN KEY(CustomerId) REFERENCES Customers(CustomerId)


CREATE TABLE CustomerAddress(
	CustomerAddressId INT IDENTITY(1,1) PRIMARY KEY,
	CustomerAddress NVARCHAR(30) NOT NULL,
	City NVARCHAR(30) NOT NULL,
	AddressState NVARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	CustomerId INT NOT NULL,
	IsActive BIT DEFAULT 1
)
ALTER TABLE CustomerAddress WITH CHECK ADD CONSTRAINT FK_AddressCustomer FOREIGN KEY(CustomerId) REFERENCES Customers(CustomerId)


CREATE TABLE ToyPlants(
	ToyPlantId INT IDENTITY(1,1) PRIMARY KEY,
	PlantName NVARCHAR(30) NOT NULL,
	PlantAddress NVARCHAR(30) NOT NULL,
	Pincode INT NOT NULL,
	IsActive BIT DEFAULT 1
)